version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: insurance
      POSTGRES_USER: insurance_user
      POSTGRES_PASSWORD: insurance_pass
    ports:
      - "5432:5432"
    networks:
      - insurance-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - insurance-net

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
    networks:
      - insurance-net

  kafdrop:
    image: obsidiandynamics/kafdrop
    depends_on:
      - kafka
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: kafka:9092
    networks:
      - insurance-net

  mockserver:
    image: mockserver/mockserver
    ports:
      - "1080:1080"
    environment:
      MOCKSERVER_INITIALIZATION_JSON_PATH: /config/init.json
    volumes:
      - ./mock-config/init.json:/config/init.json
    networks:
      - insurance-net

  adminer:
    image: adminer
    ports:
      - "8086:8080"
    depends_on:
      - postgres
    networks:
      - insurance-net


#  insurance-api:
#    build: .
#    depends_on:
#      - postgres
#      - kafka
#      - mockserver
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/insurance
#      SPRING_DATASOURCE_USERNAME: insurance_user
#      SPRING_DATASOURCE_PASSWORD: insurance_pass
#      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#      FRAUD_API_URL: http://mockserver:1080
#    ports:
#      - "8080:8080"
#    networks:
#      - insurance-net

volumes:
  postgres_data:

networks:
  insurance-net:
    driver: bridge
